name: DATAMODEL
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - archspec=0.2.3=pyhd8ed1ab_0
  - atk-1.0=2.38.0=h04ea711_2
  - babel=2.14.0=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py312hf06ca03_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=24.5.0=py312h7900ff3_0
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozendict=2.4.4=py312h9a8786e_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.13=h59595ed_1003
  - graphviz=9.0.0=h78e8752_1
  - gtk2=2.24.33=h280cfa0_4
  - gts=0.7.6=h977cf35_4
  - harfbuzz=8.5.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h7900ff3_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=hf3520f5_1
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libcurl=8.7.1=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_7
  - libgd=2.3.3=h119a65a_9
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.2=hf974151_0
  - libgomp=13.2.0=h77fa898_7
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=22_linux64_openblas
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py312hd9e9ff6_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - librsvg=2.58.0=hadf69e7_1
  - libsolv=0.7.29=ha6fb4c9_0
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_0
  - libzlib=1.2.13=h4ab18f5_6
  - loguru=0.7.2=py312h7900ff3_1
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mamba=1.5.8=py312h9460a1c_0
  - markupsafe=2.1.5=py312h98912ed_0
  - menuinst=2.1.0=py312h7900ff3_0
  - ncurses=6.5=h59595ed_0
  - numpy=1.26.4=py312heda63a1_0
  - openssl=3.3.0=h4ab18f5_3
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - pango=1.52.2=ha41ecd1_0
  - pcre2=10.43=hcad00b1_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h98912ed_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygraphviz=1.13=py312h34aa33b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - readline=8.2=h8228510_1
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.32.2=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py312h98912ed_0
  - ruamel.yaml.clib=0.2.8=py312h98912ed_0
  - setuptools=70.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.4=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.22.0=py312hd58854c_0
  - zstd=1.5.5=hfc55251_0
prefix: /home/marc-monnerat-u1/anaconda3/envs/DATAMODEL
